<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('rfid_detections', function (Blueprint $table) {
            $table->id();
            $table->uuid('event_uuid')->unique(); // generated by the device service, used for idempotency
            $table->foreignId('rfid_reader_id')->constrained('rfid_readers')->cascadeOnDelete();
            $table->string('epc');
            $table->foreignId('rfid_tag_id')->nullable()->constrained('rfid_tags')->nullOnDelete();
            $table->integer('rssi')->nullable(); // signal strength, if available
            $table->string('antenna')->nullable();
            $table->dateTime('detected_at'); // timestamp reported by the device service
            $table->dateTime('received_at'); // timestamp recorded by the server
            $table->boolean('is_duplicate')->default(false); // flagged by debounce filter
            $table->timestamps();

            $table->index(['epc', 'detected_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('rfid_detections');
    }
};
